// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team4456.robot.subsystems;

import org.usfirst.frc.team4456.robot.RobotMap;
import org.usfirst.frc.team4456.robot.commands.*;

import edu.wpi.first.wpilibj.CANTalon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Shooter extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon rightShooter = RobotMap.shooterrightShooter;
    private final CANTalon leftShooter = RobotMap.shooterleftShooter;
    private final CANTalon shootPlunger = RobotMap.shootershootPlunger;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public void speedmotors()	{
    	rightShooter.set(-1);
    	leftShooter.set(-1);
    }
    public void plunger()	{
    	shootPlunger.set(.1);
    }
    public void intake()	{
    	rightShooter.set(.1);
    	leftShooter.set(.1);
    }
    public void stopplunger()	{
    	shootPlunger.set(0);
    }
    public void stopshooter()	{
    	rightShooter.set(0);
    	leftShooter.set(0);
    }
}

