// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team4456.robot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveleftDrive;
    public static CANTalon driverightDrive;
    public static RobotDrive driveRobotDrive21;
    public static CANTalon armlowerArm;
    public static CANTalon armupperArm;
    public static CANTalon intakeintakeMotor;
    public static CANTalon shooterrightShooter;
    public static CANTalon shooterleftShooter;
    public static CANTalon shootershootPlunger;
    public static CANTalon aimscissorLift;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveleftDrive = new CANTalon(3);
        LiveWindow.addActuator("Drive", "leftDrive", driveleftDrive);
        
        driverightDrive = new CANTalon(4);
        LiveWindow.addActuator("Drive", "rightDrive", driverightDrive);
        
        driveRobotDrive21 = new RobotDrive(driveleftDrive, driverightDrive);
        
        driveRobotDrive21.setSafetyEnabled(true);
        driveRobotDrive21.setExpiration(0.1);
        driveRobotDrive21.setSensitivity(0.5);
        driveRobotDrive21.setMaxOutput(1.0);

        armlowerArm = new CANTalon(8);
        LiveWindow.addActuator("Arm", "lowerArm", armlowerArm);
        
        armupperArm = new CANTalon(9);
        LiveWindow.addActuator("Arm", "upperArm", armupperArm);
        
        intakeintakeMotor = new CANTalon(5);
        LiveWindow.addActuator("Intake", "intakeMotor", intakeintakeMotor);
        
        shooterrightShooter = new CANTalon(6);
        LiveWindow.addActuator("Shooter", "rightShooter", shooterrightShooter);
        
        shooterleftShooter = new CANTalon(7);
        LiveWindow.addActuator("Shooter", "leftShooter", shooterleftShooter);
        
        shootershootPlunger = new CANTalon(11);
        LiveWindow.addActuator("Shooter", "shootPlunger", shootershootPlunger);
        
        aimscissorLift = new CANTalon(10);
        LiveWindow.addActuator("Aim", "scissorLift", aimscissorLift);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
