// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4456.TeleopTesting.subsystems;

import org.usfirst.frc4456.TeleopTesting.RobotMap;
import org.usfirst.frc4456.TeleopTesting.commands.*;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.CANTalon.TalonControlMode;
import edu.wpi.first.wpilibj.CANSpeedController.ControlMode;
import edu.wpi.first.wpilibj.CANTalon.FeedbackDevice;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Arm extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon singleArm = RobotMap.armsingleArm;
    //private final Encoder singleEnc = RobotMap.singleArmencoder;
    private double quadEncoderPos = singleArm.getEncPosition();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	public Arm()
	{
		
		System.out.println("we r in Arm constructor");
		//this.singleArm = RobotMap.armsingleArm;;
		System.out.println("Arm.singleArm.getPIDSourceType():" + singleArm.getPIDSourceType());
		System.out.println("Arm.singleArm.getPinStateQuadIdx():" + singleArm.getPinStateQuadIdx());
		System.out.println("Arm.singleArm.getPosition():" + singleArm.getPosition());
		
		System.out.println("Arm.singleArm.getSetpoint():" + singleArm.getSetpoint());
		
		//singleArm.changeControlMode(TalonControlMode.Position);;
		//talon.setFeedbackDevice(FeedbackDevice.QuadEncoder);
		//singleArm.setPID(.25, 0.000001, 0);
		//singleArm.setPosition(0);
		//singleArm.set(singleArm.get()); //talon1 will not move
		
		//piston1 = new DoubleSolenoid(id1_1, id1_2);
		//piston2 = new DoubleSolenoid(id2_1, id2_2);
	}
    
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void arm()
    {
    	singleArm.changeControlMode(TalonControlMode.Position);
    	singleArm.setFeedbackDevice(FeedbackDevice.QuadEncoder);
    	//singleArm.setPID(1, 0, 0);
    
    
    double p = 0.1;
    double i = 0.001;
    double d = 1;
    double f = 0.0001;
    int izone = 100;
    double ramprate = 36;
    int profile = 0;
    //singleArm.setPID(p, i, d, f, izone, ramprate, profile);
    
   
    }
    public void test()
    {
    	System.out.println(singleArm.getEncPosition());
    }
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    	singleArm.pidWrite(singleArm.pidGet());
    	singleArm.setFeedbackDevice(FeedbackDevice.QuadEncoder);
    	//LiveWindow.addSensor("Arm", singleArm, quadEncoderPos);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public void primaryFor() {
    	singleArm.changeControlMode(CANTalon.TalonControlMode.PercentVbus);
    	singleArm.set(.50);
    }
    public void primaryBack() {
    	singleArm.changeControlMode(CANTalon.TalonControlMode.PercentVbus);
    	singleArm.set(-.50);
    	//singleArm.changeControlMode(CANTalon.TalonControlMode.Position);
    }
    public void stoparm()	{
    	singleArm.set(0);
    	singleArm.changeControlMode(CANTalon.TalonControlMode.Position);
		System.out.println("stopArm.singleArm.getPosition():" + singleArm.getPosition());
		System.out.println("stopArm.singleArm.getDeviceId():" + singleArm.getDeviceID());
		System.out.println("stopArm.singleArm.getControlMode():" + singleArm.getControlMode());

    }
    //ROBOT NAME: TR-8R
    public void Display()
	{
		SmartDashboard.putNumber("Position", singleArm.getPosition());
		SmartDashboard.putNumber("Current", singleArm.getOutputCurrent());
		SmartDashboard.putNumber("Speed", singleArm.getSpeed());
	}
    
    public CANTalon getSingleArm()	{
    	return this.singleArm;
    }
	
}
